### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'verbosity'

### ISSUE THREAD

**Issue by ricalessandri** [marrink-lab/polyply_1.0#107]
Maybe some temporary glitch due to vermouth/polyply? I re-cloned and re-installed vermouth and polyply (so I should be up-to-date) on my laptop and running:
```
polyply -list-lib
```
gives me:
```
Traceback (most recent call last):
  File "/Users/riccardo/miniconda3/envs/polyply/bin/polyply", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/bin/polyply", line 272, in <module>
    main()
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/bin/polyply", line 246, in main
    LOGGER.setLevel(loglevels[args.verbosity])
AttributeError: 'Namespace' object has no attribute 'verbosity'
```
Other commands seem to be working.

**Comment by fgrunewald** [comment]
should be fine now, it had to do with the way the argument parser is structured.
