### ISSUE TITLE
Exclusions in a link aren't handled by the `.ff` format

### ISSUE THREAD

**Issue by ricalessandri** [marrink-lab/polyply_1.0#134]
This is probably a https://github.com/marrink-lab/vermouth-martinize issue, but it's very relevant for the polyply library, and in particular for P3HT. When attempting to move from the `.itp` to the `.ff` format for P3HT, having the following exclusion section in the link section:

```
[ link ]
....
[ exclusions ]
; between nearest-neighbor thiophenes
   S1  +S1  +C2  +C3                    {"comment": "connection"}
   C2  +S1  +C2  +C3                    {"comment": "connection"}
   C3  +S1  +C2  +C3                    {"comment": "connection"}
```

breaks the polymer generation (the links don't get printed at all). This is the error:
```
INFO - step - reading input and library files
INFO - step - reading sequence from command
INFO - step - mapping sequence to molecule
INFO - step - applying links between residues
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 1649.19it/s]
--- Logging error ---
Traceback (most recent call last):
  File "/Users/riccardo/miniconda3/envs/polyply/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/Users/riccardo/miniconda3/envs/polyply/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/Users/riccardo/miniconda3/envs/polyply/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/Users/riccardo/miniconda3/envs/polyply/lib/python3.8/logging/__init__.py", line 367, in getMessage
    msg = str(self.msg)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/vermouth-martinize/vermouth/log_helpers.py", line 36, in __str__
    return self.fmt.format(*self.args, **self.kwargs)
KeyError: ' '
Call stack:
  File "/Users/riccardo/miniconda3/envs/polyply/bin/polyply", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/bin/polyply", line 277, in <module>
    main()
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/bin/polyply", line 273, in main
    args.func(args)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/polyply_1.0/polyply/src/gen_itp.py", line 90, in gen_itp
    LOGGER.warning(msg, n_components)
  File "/Users/riccardo/miniconda3/envs/polyply/lib/python3.8/logging/__init__.py", line 1800, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/vermouth-martinize/vermouth/log_helpers.py", line 113, in log
    super().log(level, Message(msg, args, kwargs), **kwargs)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/vermouth-martinize/vermouth/log_helpers.py", line 96, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/Users/riccardo/ric.alessandri/Repos/polyply/vermouth-martinize/vermouth/log_helpers.py", line 94, in log
    self.logger._log(level, msg, args, **kwargs)  # pylint: disable=protected-access
Message: "You molecule consists of { } disjoint parts. Perhaps links were not applied correctly.".format(*(12,), **{'extra': {'type': 'general'}})
Arguments: ()
```

**Comment by fgrunewald** [comment]
@ricalessandri you'll have to specify the edges, which go with the exclusions. This is the same thing as you need to do for edges. Look at for example this file:

**Comment by ricalessandri** [comment]
Actually, `[exclusions]` works as expected. So, I think that's preferable since more intuitive: you need to define them as you would expect you would need to. See 3cfbbeeb52a86fd53a9d7998b67cbdae542d8b84. The only problem - and what was causing the error I posted above - is one can't add the `{"comment": "connection"}` stuff.

**Comment by fgrunewald** [comment]
@ricalessandri 

I finally figured out what is going on here. For some reason exclusions are parsed differently like virtual-sites. This is a vermouth thing that obviously is not documented anywhere. However, what happens is that exclusion when they have the "{}" syntax are parsed in a funny manner such that "comment" ends up as node attribute. In a normal case it would be stripped from the exclusions. 

To fix this you need to use the same syntax as with VS:

```
[ exclusions ]
1 2 -- {"comment": "random"}
```

**Comment by fgrunewald** [comment]
I added a section about this in the wiki tutorial.
